(local WINDOW-W 1280)
(local WINDOW-H 720)
(local GROUND-Y 580)
(local TURRET-X (/ WINDOW-W 2))
(local TURRET-Y GROUND-Y)
(local TURRET-BARREL-LEN 36)

(local BUILDING-COUNT 5)
(local BUILDING-W 44)
(local BUILDING-H 52)
(local BUILDING-SPACING 56)
(local MAX-HP 100)

(local PLANE-HP 100)
(local BULLET-DMG 10)
(local MISSILE-DMG 100)
(local WRECK-IMPACT-DMG 20)

(local ROUND-TIME 60)
(local MISSILE-COOLDOWN 20)
(local SALVO-COUNT 10)
(local SALVO-INTERVAL 0.5)
(local MISSILE-CHASE-TIME 5)

(local RED-MIN 4)
(local RED-MAX 6)
(local GREEN-MIN 3)
(local GREEN-MAX 4)
(local GREY-TARGET 3)

(local RED-SPEED 115)
(local GREEN-SPEED 135)
(local GREY-SPEED 95)
(local RED-TURN-RATE 2.0)
(local GREEN-TURN-RATE 2.4)
(local GRAVITY 420)

(local TURRET-FIRE-INTERVAL (/ 1 10))
(local PLANE-FIRE-INTERVAL (/ 1 1.5))
(local BULLET-SPEED 420)
(local MISSILE-SPEED 300)

(local PLANE-R 14)
(local PLANE-EDGE-MARGIN 100)
(local BULLET-R 3)
(local MISSILE-R 5)
(local BUILDING-HIT-R 28)

(local SPAWN-INTERVAL 2.5)
(local GREY-SPAWN-INTERVAL 4.0)
(local EVADE-DURATION 2)

{:WINDOW-W WINDOW-W
 :WINDOW-H WINDOW-H
 :GROUND-Y GROUND-Y
 :TURRET-X TURRET-X
 :TURRET-Y TURRET-Y
 :TURRET-BARREL-LEN TURRET-BARREL-LEN
 :BUILDING-COUNT BUILDING-COUNT
 :BUILDING-W BUILDING-W
 :BUILDING-H BUILDING-H
 :BUILDING-SPACING BUILDING-SPACING
 :MAX-HP MAX-HP
 :PLANE-HP PLANE-HP
 :BULLET-DMG BULLET-DMG
 :MISSILE-DMG MISSILE-DMG
 :WRECK-IMPACT-DMG WRECK-IMPACT-DMG
 :ROUND-TIME ROUND-TIME
 :MISSILE-COOLDOWN MISSILE-COOLDOWN
 :SALVO-COUNT SALVO-COUNT
 :SALVO-INTERVAL SALVO-INTERVAL
 :MISSILE-CHASE-TIME MISSILE-CHASE-TIME
 :RED-MIN RED-MIN
 :RED-MAX RED-MAX
 :GREEN-MIN GREEN-MIN
 :GREEN-MAX GREEN-MAX
 :GREY-TARGET GREY-TARGET
 :RED-SPEED RED-SPEED
 :GREEN-SPEED GREEN-SPEED
 :GREY-SPEED GREY-SPEED
 :RED-TURN-RATE RED-TURN-RATE
 :GREEN-TURN-RATE GREEN-TURN-RATE
 :GRAVITY GRAVITY
 :TURRET-FIRE-INTERVAL TURRET-FIRE-INTERVAL
 :PLANE-FIRE-INTERVAL PLANE-FIRE-INTERVAL
 :BULLET-SPEED BULLET-SPEED
 :MISSILE-SPEED MISSILE-SPEED
 :PLANE-R PLANE-R
 :PLANE-EDGE-MARGIN PLANE-EDGE-MARGIN
 :BULLET-R BULLET-R
 :MISSILE-R MISSILE-R
 :BUILDING-HIT-R BUILDING-HIT-R
 :SPAWN-INTERVAL SPAWN-INTERVAL
 :GREY-SPAWN-INTERVAL GREY-SPAWN-INTERVAL
 :EVADE-DURATION EVADE-DURATION}
