(local WINDOW-W 800)
(local WINDOW-H 480)
(local GROUND-Y (- WINDOW-H 60))
(local GRAVITY 900)
(local PHYSICS-DT (/ 1 120))
(local SUBSTEPS 4)
(local MAX-ACCUM-STEPS 8)
(local OFF-SCREEN-MARGIN 40)

(local BRICK-SIZE 8)
(local MAX-BUILDING-W-BRICKS 14)
(local MAX-BUILDING-H-BRICKS 22)
(local MIN-BUILDING-W-BRICKS 4)
(local MIN-BUILDING-H-BRICKS 6)
(local BUILDINGS-PER-SIDE-MIN 1)
(local BUILDINGS-PER-SIDE-MAX 3)
(local SIDE-MARGIN 16)
(local EXCLUDE-RADIUS-X 120)
(local EXCLUDE-RADIUS-Y 180)

(local BASE-X (/ WINDOW-W 2))
(local BASE-Y (- GROUND-Y 24))
(local BASE-R 18)
(local ARM-LEN 88)
(local ARM-THICK 8)
(local BALL-R 14)
(local BALL-MASS 40)
(local BRICK-MASS 1)
(local CHAIN-LEN 130)
(local TIP-MASS 8)

(local MOTOR-K 4200)
(local MOTOR-DAMP 28)
(local CABLE-STIFFNESS 18000)
(local RESTITUTION 0.15)
(local FRICTION 0.35)
(local GROUND-FRICTION 0.5)
(local MAX-BRICKS 1500)

(local SPATIAL-CELL-SIZE 16)

{:WINDOW-W WINDOW-W
 :WINDOW-H WINDOW-H
 :GROUND-Y GROUND-Y
 :GRAVITY GRAVITY
 :PHYSICS-DT PHYSICS-DT
 :SUBSTEPS SUBSTEPS
 :MAX-ACCUM-STEPS MAX-ACCUM-STEPS
 :OFF-SCREEN-MARGIN OFF-SCREEN-MARGIN
 :BRICK-SIZE BRICK-SIZE
 :MAX-BUILDING-W-BRICKS MAX-BUILDING-W-BRICKS
 :MAX-BUILDING-H-BRICKS MAX-BUILDING-H-BRICKS
 :MIN-BUILDING-W-BRICKS MIN-BUILDING-W-BRICKS
 :MIN-BUILDING-H-BRICKS MIN-BUILDING-H-BRICKS
 :BUILDINGS-PER-SIDE-MIN BUILDINGS-PER-SIDE-MIN
 :BUILDINGS-PER-SIDE-MAX BUILDINGS-PER-SIDE-MAX
 :SIDE-MARGIN SIDE-MARGIN
 :EXCLUDE-RADIUS-X EXCLUDE-RADIUS-X
 :EXCLUDE-RADIUS-Y EXCLUDE-RADIUS-Y
 :BASE-X BASE-X
 :BASE-Y BASE-Y
 :BASE-R BASE-R
 :ARM-LEN ARM-LEN
 :ARM-THICK ARM-THICK
 :BALL-R BALL-R
 :BALL-MASS BALL-MASS
 :BRICK-MASS BRICK-MASS
 :CHAIN-LEN CHAIN-LEN
 :TIP-MASS TIP-MASS
 :MOTOR-K MOTOR-K
 :MOTOR-DAMP MOTOR-DAMP
 :CABLE-STIFFNESS CABLE-STIFFNESS
 :RESTITUTION RESTITUTION
 :FRICTION FRICTION
 :GROUND-FRICTION GROUND-FRICTION
 :MAX-BRICKS MAX-BRICKS
 :SPATIAL-CELL-SIZE SPATIAL-CELL-SIZE
 :brick-half (/ BRICK-SIZE 2)}
