(local WINDOW-W 800)
(local WINDOW-H 480)
(local GROUND-Y (- WINDOW-H 60))
(local GRAVITY 900)
(local MAX-DT (/ 1 30))
(local OFF-SCREEN-MARGIN 40)

(local BRICK-SIZE 8)
(local MAX-BUILDING-W-BRICKS 14)
(local MAX-BUILDING-H-BRICKS 22)
(local MIN-BUILDING-W-BRICKS 4)
(local MIN-BUILDING-H-BRICKS 6)
(local BUILDINGS-PER-SIDE-MIN 1)
(local BUILDINGS-PER-SIDE-MAX 3)
(local SIDE-MARGIN 16)
(local EXCLUDE-RADIUS-X 120)
(local EXCLUDE-RADIUS-Y 180)

(local BASE-X (/ WINDOW-W 2))
(local BASE-Y (- GROUND-Y 24))
(local BASE-R 18)
(local ARM-LEN 88)
(local ARM-THICK 8)
(local BALL-R 14)
(local CHAIN-LEN 130)

(local ARM-DENSITY 0.8)
(local BALL-DENSITY 2.5)
(local BRICK-DENSITY 0.15)

(local FIXTURE-FRICTION 0.45)
(local FIXTURE-RESTITUTION 0.12)

(local MOTOR-MAX-TORQUE 800000)
(local MOTOR-SPEED-GAIN 12)

(local CAT-GROUND 1)
(local CAT-CRANE 2)
(local CAT-BALL 4)
(local CAT-BRICK 8)

(local MAX-BRICKS 1500)

(local BRICK-SETTLE-STEPS 50)
(local BRICK-SETTLE-DT MAX-DT)

(local ARM-REST-ANGLE (- (/ math.pi 2)))

{:WINDOW-W WINDOW-W
 :WINDOW-H WINDOW-H
 :GROUND-Y GROUND-Y
 :GRAVITY GRAVITY
 :MAX-DT MAX-DT
 :OFF-SCREEN-MARGIN OFF-SCREEN-MARGIN
 :BRICK-SIZE BRICK-SIZE
 :MAX-BUILDING-W-BRICKS MAX-BUILDING-W-BRICKS
 :MAX-BUILDING-H-BRICKS MAX-BUILDING-H-BRICKS
 :MIN-BUILDING-W-BRICKS MIN-BUILDING-W-BRICKS
 :MIN-BUILDING-H-BRICKS MIN-BUILDING-H-BRICKS
 :BUILDINGS-PER-SIDE-MIN BUILDINGS-PER-SIDE-MIN
 :BUILDINGS-PER-SIDE-MAX BUILDINGS-PER-SIDE-MAX
 :SIDE-MARGIN SIDE-MARGIN
 :EXCLUDE-RADIUS-X EXCLUDE-RADIUS-X
 :EXCLUDE-RADIUS-Y EXCLUDE-RADIUS-Y
 :BASE-X BASE-X
 :BASE-Y BASE-Y
 :BASE-R BASE-R
 :ARM-LEN ARM-LEN
 :ARM-THICK ARM-THICK
 :BALL-R BALL-R
 :CHAIN-LEN CHAIN-LEN
 :ARM-DENSITY ARM-DENSITY
 :BALL-DENSITY BALL-DENSITY
 :BRICK-DENSITY BRICK-DENSITY
 :FIXTURE-FRICTION FIXTURE-FRICTION
 :FIXTURE-RESTITUTION FIXTURE-RESTITUTION
 :MOTOR-MAX-TORQUE MOTOR-MAX-TORQUE
 :MOTOR-SPEED-GAIN MOTOR-SPEED-GAIN
 :CAT-GROUND CAT-GROUND
 :CAT-CRANE CAT-CRANE
 :CAT-BALL CAT-BALL
 :CAT-BRICK CAT-BRICK
 :MAX-BRICKS MAX-BRICKS
 :BRICK-SETTLE-STEPS BRICK-SETTLE-STEPS
 :BRICK-SETTLE-DT BRICK-SETTLE-DT
 :ARM-REST-ANGLE ARM-REST-ANGLE
 :brick-half (/ BRICK-SIZE 2)}
