(local PANE_W 800)
(local PANE_H 480)
(local GRAVITY 900)
(local MOVE_SPEED 220)
(local AIR_CONTROL 0.7)
(local JUMP_VEL -380)
(local MAX_STEP 48)
(local MAX_SLOPE 0.65)
(local SAMPLE_DX 40)
(local CAPSULE_R 12)
(local CAPSULE_H 36)
(local PANES_AHEAD 2)
(local FLOOR_BASE (- PANE_H 80))
(local FLOOR_MIN (- PANE_H 200))
(local FLOOR_MAX (- PANE_H 60))
(local CAMERA_LEAD (/ PANE_W 3))
(local GROUND_EPSILON 2)
(local WALK_STEP_PX 12)
(local WALK_VX_EPSILON 5)

(fn capsule-half-body []
  (- (/ CAPSULE_H 2) CAPSULE_R))

{:PANE_W PANE_W
 :PANE_H PANE_H
 :GRAVITY GRAVITY
 :MOVE_SPEED MOVE_SPEED
 :AIR_CONTROL AIR_CONTROL
 :JUMP_VEL JUMP_VEL
 :MAX_STEP MAX_STEP
 :MAX_SLOPE MAX_SLOPE
 :SAMPLE_DX SAMPLE_DX
 :CAPSULE_R CAPSULE_R
 :CAPSULE_H CAPSULE_H
 :PANES_AHEAD PANES_AHEAD
 :FLOOR_BASE FLOOR_BASE
 :FLOOR_MIN FLOOR_MIN
 :FLOOR_MAX FLOOR_MAX
 :CAMERA_LEAD CAMERA_LEAD
 :GROUND_EPSILON GROUND_EPSILON
 :WALK_STEP_PX WALK_STEP_PX
 :WALK_VX_EPSILON WALK_VX_EPSILON
 :capsule-half-body capsule-half-body}
