name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.4.6"

      - uses: leafo/gh-actions-luarocks@v6

      - name: Install Fennel
        run: luarocks install fennel 1.6.1-1

      - name: Install deps.fnl
        run: |
          mkdir -p "$HOME/.local/bin"
          git clone --depth 1 https://gitlab.com/andreyorst/deps.fnl /tmp/deps.fnl
          cp /tmp/deps.fnl/deps "$HOME/.local/bin/deps"
          chmod +x "$HOME/.local/bin/deps"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Run tests
        env:
          DEPS_NO_PROMPT: "true"
        run: deps --profiles dev --no-prompt tasks/run-tests
